### ISSUE TITLE
RSS feed seems broken

### ISSUE THREAD

**Issue by aciccarello** [odoe/odoenet#18]
Hi, looks like you have some great content on your blog. But the RSS link in the footer (https://odoe.net/atom.xml) just loads the homepage. It might also be good to allow [autodiscovery of your RSS feed](https://www.rssboard.org/rss-autodiscovery) via a header element to help tools find your feed.

```
<html>
  <head>
    <title>The RSS Blog</title>
    <link rel="alternate" type="application/rss+xml" title="RSS"
      href="http://feeds.feedburner.com/TheRssBlog">
  </head>
  <body>
    <!-- the web page's contents -->
  </body>
</html> 
```

**Comment by odoe** [comment]
Ah, thanks! I figured out what it is. It has to do with the `dojo` build cache. I'll fix this up in next build and thanks for the header suggestion!

**Comment by odoe** [comment]
I think this has been fixed, seems good so far. Never mind, some links broken
